service:
  GF-ET:
    service_id: "GF-ET"
    service_name: "Gold Finger"
    short_code: "1111"
    operator_id: "28"
    api_key: "ivvT4azDdWN3UTgMPAOelOnIsscSGSKJ"
    api_secret: "vZkXOxb70S9Os6DfYZKyay+60brtDRZZVHFYNBayA7E5dnpBf2Xsu5drtNtBty1D"
#    api_secret: "vZkXOxb70S9Os6DfYZKyay%2b60brtDRZZVHFYNBayA7E5dnpBf2Xsu5drtNtBty1D"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "GF"
    product_name: "Gold Finger"
    description: "amazing Mobile Games"
    description_ar: " ألعاب مدهشة "
    service: "game"
    content: "games"
    content_ar: " ألعاب جديدة تضاف"
    limit_sub_num: 500
    camp_id: 5
    application_id: "12"
    country_id: "247"
    cp_id : "9"
    msg_text: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.goldfingervr.com/. "
    url_post: "http://ar.goldfingervr.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    tnc_url: ""

  GF-DU:
    service_id: "GF-DU"
    service_name: "Gold Finger"
    short_code: "3246"
    operator_id: "32"
    api_key: "7xlO9uuUktUka8CFlHPfJsDzzlaS51vD"
    api_secret: "/JACZwinCd+WVSd+mNxJFAMvzWNWKYXmia1oA+6vPrUj7c7eMI29Yf1h+b6zd+Un"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "GF"
    product_name: "Gold Finger"
    description: "amazing Mobile Games"
    description_ar: " ألعاب مدهشة "
    service: "game"
    content: "games"
    content_ar: " ألعاب جديدة تضاف"
    limit_sub_num: 500
    camp_id: 4
    application_id: "12"
    country_id: "247"
    cp_id: "9"
    url_post: "http://ar.goldfingervr.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    msg_text: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.goldfingervr.com/. "

  MA-ET:
    service_id: "MA-ET"
    service_name: "My Anime"
    short_code: "1111"
    operator_id: "28"
    api_key: "5MC0F8sB2INDoYujroXAKhBml1wkpWBp"
    api_secret: "7erVdrMdoavtY1MPQy/gJn7L63B/tj2+nHr+ccwyOYQDSCoa5b3EQOUcI4F0sHLh"
    rurl: "http://ar.mranimes.com/thank"
    key_word: "MA"
    product_name: "My Anime"
    description: "amazing Animated Videos"
    description_ar: " مقاطع فيديو متحركة مذهلة  "
    service: "anime"
    content: "videos"
    content_ar: " تتم إضافة مقاطع فيديو جديدة "
    limit_sub_num: 500
    camp_id: 7
    application_id : "13"
    country_id : "247"
    cp_id : "9"
    msg_text: "Thank you for subscribing to My Anime service. You can visit the portal on http://ar.mranimes.com/"
    url_post: "http://ar.mranimes.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    tnc_url: ""
  MA-DU:
    service_id: "MA-DU"
    service_name: "My Anime"
    short_code: "3246"
    operator_id: "32"
    api_key: "xxKHAnaleglcp6He9KEk85pABMJSXmwK"
    api_secret: "ncVAQM4VE8SrRqZAKW4MWtia/66PBs37c8PtoQgUReU02Mjwe06QSl+P1OIwJTx0"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "MA"
    product_name: "My Anime"
    description: "amazing Animated Videos"
    description_ar: " مقاطع فيديو متحركة مذهلة  "
    service: "anime"
    content: "videos"
    content_ar: " تتم إضافة مقاطع فيديو جديدة "
    limit_sub_num: 500
    camp_id: 6
    application_id: "13"
    country_id: "247"
    cp_id: "9"
    msg_text: "Thank you for subscribing to My Anime service. You can visit the portal on http://ar.mranimes.com/"
    url_post: "http://ar.mranimes.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  POM-ET:
    service_id: "POM-ET"
    service_name: "Poi Movie"
    short_code: "1111"
    operator_id: "28"
    api_key: "Znvg0aF42RLalt5nFTnsUGbc4Fc5h2Sf"
    api_secret: "tqhkRFEbpXhpk31xkCQjSmao9dlrsXOk3wZYSaJYnWROlVxJVUgAr+wQ/Lqiyj1x"
    rurl: "http://ar.mrmoviesite.com/thank"
    key_word: "POM"
    product_name: "Poi movie"
    description: "last movie"
    description_ar: " أحدث الأفلام "
    service: "movie"
    content: "movies"
    content_ar: " تمت إضافة أفلام جديدة "
    limit_sub_num: 500
    camp_id: 9
    application_id: "14"
    country_id: "247"
    cp_id: "9"
    msgText : "Thank you for subscribing to Poi Movie service. You can visit the portal on http://ar.mrmoviesite.com/. "
    url_post: "http://ar.mrmoviesite.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    tnc_url: ""
  POM-DU:
    service_id: "POM-DU"
    service_name: "Poi Movie"
    short_code: "3246"
    operator_id: "32"
    api_key: "czoFxiJ3HfS6EZwZjHhIe41v3J1AizyS"
    api_secret: "bB9csgdZ7wkt9ryFQXDx8y7/ozlv9gmgCkcQIBZKOLDoOSqiVd5ri9Pf0N8SdgDw"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "POM"
    product_name: "Poi movie"
    description: "last movie"
    description_ar: " أحدث الأفلام "
    service: "movie"
    content: "movies"
    content_ar: " تمت إضافة أفلام جديدة "
    limit_sub_num: 500
    camp_id: 8
    application_id: "14"
    country_id: "247"
    cp_id: "9"
    msgText: "Thank you for subscribing to Poi Movie service. You can visit the portal on http://ar.mrmoviesite.com/. "
    url_post: "http://ar.mrmoviesite.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  BB-ET:
    service_id: "BB-ET"
    service_name: "Bodybuild"
    short_code: "1111"
    operator_id: "28"
    api_key: "kLJ6ToymFc5yGHP6N6jYM0fq9qJdAIat"
    api_secret: "diy3QXB6J5Ekp7BBXxvnv0ZEhuGLMAdgTJoy1zq7FOBvXviLG8RM8/IZZf8f0r4E"
    rurl: "http://at.fitnessnice.com/thank"
    key_word: "BB"
    product_name: "Bodybuild"
    description: "weight loss workout plan and muscle building tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "build"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 11
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://at.fitnessnice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Bodybuild service. You can visit the portal on http://at.fitnessnice.com/. "
    tnc_url: ""
  BB-DU:
    service_id: "BB-DU"
    service_name: "Bodybuild"
    short_code: "3246"
    operator_id: "32"
    api_key: "19cN7sCClgx2OLjlkHwHcTKcCdqxdY6G"
    api_secret: "O0yYy5tPQ7noIfksc3YA0nJc3ch+AEoI6GbWcdb1vpMnWfV1YFR8LILj4ooHjwKn"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "BB"
    product_name: "Bodybuild"
    description: "weight loss workout plan and muscle building tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "build"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 10
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post : "http://at.fitnessnice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Bodybuild service. You can visit the portal on http://at.fitnessnice.com/. "
  RC-ET:
    service_id: "RC-ET"
    service_name: "Recipe"
    short_code: "1111"
    operator_id: "28"
    api_key: "kLJ6ToymFc5yGHP6N6jYM0fq9qJdAIat"
    api_secret: "diy3QXB6J5Ekp7BBXxvnv0ZEhuGLMAdgTJoy1zq7FOBvXviLG8RM8/IZZf8f0r4E"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "RC"
    product_name: "Recipe"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "recipe"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://en.recipenice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Recipe service. You can visit the portal on http://en.recipenice.com/. "
    tnc_url: ""
  RC-DU:
    service_id: "RC-DU"
    service_name: "Recipe"
    short_code: "3246"
    operator_id: "32"
    api_key: "19cN7sCClgx2OLjlkHwHcTKcCdqxdY6G"
    api_secret: "O0yYy5tPQ7noIfksc3YA0nJc3ch+AEoI6GbWcdb1vpMnWfV1YFR8LILj4ooHjwKn"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "RC"
    product_name: "Recipe"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "recipe"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://en.recipenice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Recipe service. You can visit the portal on http://en.recipenice.com/. "
  EB-ET:
    service_id: "EB-ET"
    service_name: "Ebook"
    short_code: "1111"
    operator_id: "28"
    api_key: "kLJ6ToymFc5yGHP6N6jYM0fq9qJdAIat"
    api_secret: "diy3QXB6J5Ekp7BBXxvnv0ZEhuGLMAdgTJoy1zq7FOBvXviLG8RM8/IZZf8f0r4E"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "EB"
    product_name: "Ebook"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "ebook"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://en.ebooknice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Ebook service. You can visit the portal on http://en.ebooknice.com/. "
    tnc_url: ""
  EB-DU:
    service_id: "EB-DU"
    service_name: "Ebook"
    short_code: "3246"
    operator_id: "32"
    api_key: "19cN7sCClgx2OLjlkHwHcTKcCdqxdY6G"
    api_secret: "O0yYy5tPQ7noIfksc3YA0nJc3ch+AEoI6GbWcdb1vpMnWfV1YFR8LILj4ooHjwKn"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "EB"
    product_name: "Ebook"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "ebook"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://en.ebooknice.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to Ebook service. You can visit the portal on http://en.ebooknice.com/. "
  FN-ET:
    service_id: "FN-ET"
    service_name: "FNGame"
    short_code: "1111"
    operator_id: "28"
    api_key: "kLJ6ToymFc5yGHP6N6jYM0fq9qJdAIat"
    api_secret: "diy3QXB6J5Ekp7BBXxvnv0ZEhuGLMAdgTJoy1zq7FOBvXviLG8RM8/IZZf8f0r4E"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "FN"
    product_name: "FNGame"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "fngame"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://fn.3499games.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to FNGame service. You can visit the portal on http://fn.3499games.com/. "
    tnc_url: ""
  FN-DU:
    service_id: "FN-DU"
    service_name: "FNGame"
    short_code: "3246"
    operator_id: "32"
    api_key: "19cN7sCClgx2OLjlkHwHcTKcCdqxdY6G"
    api_secret: "O0yYy5tPQ7noIfksc3YA0nJc3ch+AEoI6GbWcdb1vpMnWfV1YFR8LILj4ooHjwKn"
    rurl: "http://kg.argameloft.com/thank"
    key_word: "FN"
    product_name: "FNGame"
    description: "weight loss workout plan and muscle recipe tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "fngame"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 500
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://fn.3499games.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
    msg_text: "Thank you for subscribing to FNGame service. You can visit the portal on http://fn.3499games.com/. "
