service:
  GF-ET:
    service_id: "GF-ET"
    service_name: "Gold Finger"
    short_code: "1111"
    operator_id: "28"
    api_key: "ivvT4azDdWN3UTgMPAOelOnIsscSGSKJ"
    api_secret: "vZkXOxb70S9Os6DfYZKyay+60brtDRZZVHFYNBayA7E5dnpBf2Xsu5drtNtBty1D"
    rurl: "http://ku.g0finger.com/thank/gf?trackID="
    key_word: "GF"
    product_name: "Gold Finger"
    description: "amazing Mobile Games"
    description_ar: " ألعاب مدهشة "
    service: "game"
    content: "games"
    content_ar: " ألعاب جديدة تضاف"
    limit_sub_num: 50
    camp_id: 36
    application_id: "12"
    country_id: "247"
    cp_id : "9"
    msg_text: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ku.g0finger.com/. "
    url_post: "http://ku.g0finger.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"

  GF-DU:
    service_id: "GF-DU"
    service_name: "Gold Finger"
    short_code: "3246"
    operator_id: "32"
    api_key: "7xlO9uuUktUka8CFlHPfJsDzzlaS51vD"
    api_secret: "/JACZwinCd+WVSd+mNxJFAMvzWNWKYXmia1oA+6vPrUj7c7eMI29Yf1h+b6zd+Un"
    rurl: "http://kg.foxseek.com/thank/gf?trackID="
    key_word: "GF"
    product_name: "Gold Finger"
    description: "amazing Mobile Games"
    description_ar: " ألعاب مدهشة "
    service: "game"
    content: "games"
    content_ar: " ألعاب جديدة تضاف"
    limit_sub_num: 50
    camp_id: 36
    application_id: "12"
    country_id: "247"
    cp_id: "9"
    url_post: "http://ku.g0finger.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"

  MYA-ET:
    service_id: "MYA-ET"
    service_name: "My Anime"
    short_code: "1111"
    operator_id: "28"
    api_key: "5MC0F8sB2INDoYujroXAKhBml1wkpWBp"
    api_secret: "7erVdrMdoavtY1MPQy/gJn7L63B/tj2+nHr+ccwyOYQDSCoa5b3EQOUcI4F0sHLh"
    rurl: "http://ar.abanime.com/thank/trackID="
    key_word: "MYA"
    product_name: "My Anime"
    description: "amazing Animated Videos"
    description_ar: " مقاطع فيديو متحركة مذهلة  "
    service: "anime"
    content: "videos"
    content_ar: " تتم إضافة مقاطع فيديو جديدة "
    limit_sub_num: 50
    camp_id: 36
    application_id : "13"
    country_id : "247"
    cp_id : "9"
    msg_text: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.abanime.com/"
    url_post: "http://ar.abanime.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  MYA-DU:
    service_id: "MYA-DU"
    service_name: "My Anime"
    short_code: "3246"
    operator_id: "32"
    api_key: "xxKHAnaleglcp6He9KEk85pABMJSXmwK"
    api_secret: "ncVAQM4VE8SrRqZAKW4MWtia/66PBs37c8PtoQgUReU02Mjwe06QSl+P1OIwJTx0"
    rurl: "http://kg.foxseek.com/thank/mya?trackID="
    key_word: "MYA"
    product_name: "My Anime"
    description: "amazing Animated Videos"
    description_ar: " مقاطع فيديو متحركة مذهلة  "
    service: "anime"
    content: "videos"
    content_ar: " تتم إضافة مقاطع فيديو جديدة "
    limit_sub_num: 50
    camp_id: 36
    application_id: "13"
    country_id: "247"
    cp_id: "9"
    msg_text: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.abanime.com/"
    url_post: "http://ar.abanime.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  POM-ET:
    service_id: "POM-ET"
    service_name: "Poi Movie"
    short_code: "1111"
    operator_id: "28"
    api_key: "Znvg0aF42RLalt5nFTnsUGbc4Fc5h2Sf"
    api_secret: "tqhkRFEbpXhpk31xkCQjSmao9dlrsXOk3wZYSaJYnWROlVxJVUgAr+wQ/Lqiyj1x"
    rurl: "http://ar.poimovie.com/thank/trackID=?"
    key_word: "POM"
    product_name: "Poi movie"
    description: "last movie"
    description_ar: " أحدث الأفلام "
    service: "movie"
    content: "movies"
    content_ar: " تمت إضافة أفلام جديدة "
    limit_sub_num: 50
    camp_id: 36
    application_id: "14"
    country_id: "247"
    cp_id: "9"
    msgText : "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.poimovie.com/. "
    url_post: "http://ar.poimovie.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  POM-DU:
    service_id: "POM-DU"
    service_name: "Poi Movie"
    short_code: "3246"
    operator_id: "32"
    api_key: "czoFxiJ3HfS6EZwZjHhIe41v3J1AizyS"
    api_secret: "bB9csgdZ7wkt9ryFQXDx8y7/ozlv9gmgCkcQIBZKOLDoOSqiVd5ri9Pf0N8SdgDw"
    rurl: "http://kg.foxseek.com/thank/pom?trackID="
    key_word: "POM"
    product_name: "Poi movie"
    description: "last movie"
    description_ar: " أحدث الأفلام "
    service: "movie"
    content: "movies"
    content_ar: " تمت إضافة أفلام جديدة "
    limit_sub_num: 50
    camp_id: 36
    application_id: "14"
    country_id: "247"
    cp_id: "9"
    msgText: "Thank you for subscribing to Gold Finger service. You can visit the portal on http://ar.poimovie.com/. "
    url_post: "http://ar.poimovie.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  BB-ET:
    service_id: "BB-ET"
    service_name: "Bodybuild"
    short_code: "1111"
    operator_id: "28"
    api_key: "kLJ6ToymFc5yGHP6N6jYM0fq9qJdAIat"
    api_secret: "diy3QXB6J5Ekp7BBXxvnv0ZEhuGLMAdgTJoy1zq7FOBvXviLG8RM8/IZZf8f0r4E"
    rurl: "http://ar.fit8tube.com/thank/trackID="
    key_word: "BB"
    product_name: "Bodybuild"
    description: "weight loss workout plan and muscle building tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "build"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 30
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post: "http://ar.fit8tube.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"
  BB-DU:
    service_id: "BB-DU"
    service_name: "Bodybuild"
    short_code: "3246"
    operator_id: "32"
    api_key: "19cN7sCClgx2OLjlkHwHcTKcCdqxdY6G"
    api_secret: "O0yYy5tPQ7noIfksc3YA0nJc3ch+AEoI6GbWcdb1vpMnWfV1YFR8LILj4ooHjwKn"
    rurl: "http://kg.foxseek.com/thank/bb?trackID="
    key_word: "BB"
    product_name: "Bodybuild"
    description: "weight loss workout plan and muscle building tricks"
    description_ar: " خطة تمارين لفقدان الوزن وحيل بناء العضلات "
    service: "build"
    content: "content"
    content_ar: " محتوى جديد يضاف "
    limit_sub_num: 30
    camp_id: 50
    application_id: "15"
    country_id: "247"
    cp_id: "9"
    url_post : "http://ar.fit8tube.com/"
    req_url: "user/add?name={msisdn}&pass={pass}"
    price: "11"

